<a href="https://colab.research.google.com/github/AlecTraas/computational-geo-lab/blob/main/GoodPracticesAndTips.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Follow these good practices guidelines to keep your notebook clean

## Keep imports in their own cell. If you have many imports, you can separate them into multiple cells and keep similar ones together.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Define functions in their own cells. You should have a main function for whatever task we are doing for that week.

In [2]:
def AuxFn1():
  # Do something
  pass

In [3]:
def AuxFn2():
  # Do something else
  pass

In [4]:
def Convex_Hull(points):
  # convex hull computation goes in here. Any auxiliary function should be defined in previous cells.
  AuxFn1()
  AuxFn2()

  pass

# Numpy Tips

## Numpy arrays are defined from lists of lists (of lists, of lists, etc.)

np.array() takes a single list as an argument. This list must contain further lists of the same size.

In [5]:
points = np.array( [ [1,1], [2,1], [-1, 3] ] )

In [6]:
print(points)

[[ 1  1]
 [ 2  1]
 [-1  3]]


In [7]:
print(points.shape)

(3, 2)


Example of multidimensionality. Note the final lists that contains numbers are all the same size.

In [12]:
multi_dim_array = np.array( [ [ [1,2,3], [4,5,6] ] , [ [7,8,9], [10, 11, 12] ] ] )

In [9]:
print(multi_dim_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


This array contains 2 lists, each containing 2 lists, which then contain 3 elements. The brackets above should make this clear.

In [10]:
print(multi_dim_array.shape)

(2, 2, 3)


To index an numpy array, you can list out of the index according to the shape of the array. Each dimension is called an "axis".

In [17]:
# Here, we take the second element in the first axis, i.e. [ [7,8,9], [10, 11, 12] ]. Then take the first element along the second axis, i.e. [7,8,9]. Finally take the third element along the third axis, i.e. 9
print(multi_dim_array[1, 0, 2])

9


Use a colon to index every element of that axis simultaneously. This is known as slicing.

In [19]:
# Here, for all elements in the first axis, we take the first element along the second axis, i.e. [1,2,3] AND [7,8,9]. For each of these elements, take the second element along the third axis, i.e. 2 AND 8.
print(multi_dim_array[:, 0, 1])

[2 8]


In [20]:
print(multi_dim_array[0, :, 0])

[1 4]


In [21]:
print(multi_dim_array[0, 1, :])

[4 5 6]
