<a href="https://colab.research.google.com/github/AlecTraas/computational-geo-lab/blob/main/Colab/Lam/Demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import matplotlib.pyplot as plt

In [21]:
points = np.array([ [0,0],
                    [1,1],
                    [2,3],
                    [-4,10] ])

In [16]:
new_indices = np.argsort(np.array([ 3,6,-1,2 ]))

In [14]:
f = np.array([3,6,-1,2])

In [18]:
f = f[new_indices]

In [30]:
x_vals = points[ : , 0]

In [31]:
indices = np.argsort(x_vals)

In [32]:
points[indices]

array([[ 0,  0],
       [ 1,  1],
       [ 2,  3],
       [-4, 10]])

In [28]:
points[:, 0]

array([ 0,  1,  2, -4])

In [29]:
points[:, 1]

array([ 0,  1,  3, 10])